// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TwitchGames.Ttny.Dal.Entities;

namespace TwitchGames.Ttny.Dal.Migrations
{
    [DbContext(typeof(TtnyDbContext))]
    partial class TtnyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TwitchGames.Ttny.Dal.Entities.TownEntity.Town", b =>
                {
                    b.Property<Guid>("TownId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Alive")
                        .HasColumnType("bit");

                    b.Property<long>("Defense")
                        .HasColumnType("bigint");

                    b.Property<long>("Food")
                        .HasColumnType("bigint");

                    b.Property<long>("NextAttackSize")
                        .HasColumnType("bigint");

                    b.Property<long>("Wood")
                        .HasColumnType("bigint");

                    b.HasKey("TownId");

                    b.ToTable("Towns");
                });

            modelBuilder.Entity("TwitchGames.Ttny.Dal.Entities.TownEventEntity.TownEvent", b =>
                {
                    b.Property<Guid>("TownEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TownId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TownEventId");

                    b.HasIndex("TownId");

                    b.HasIndex("UserId");

                    b.ToTable("TownEvents");
                });

            modelBuilder.Entity("TwitchGames.Ttny.Dal.Entities.TownUserEntity.TownUser", b =>
                {
                    b.Property<Guid>("TownId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Alive")
                        .HasColumnType("bit");

                    b.Property<bool>("HaveAction")
                        .HasColumnType("bit");

                    b.HasKey("TownId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TownUsers");
                });

            modelBuilder.Entity("TwitchGames.Ttny.Dal.Entities.UserEntity.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TwitchGames.Ttny.Dal.Entities.TownEventEntity.TownEvent", b =>
                {
                    b.HasOne("TwitchGames.Ttny.Dal.Entities.TownEntity.Town", "Town")
                        .WithMany("TownEvents")
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TwitchGames.Ttny.Dal.Entities.UserEntity.User", "User")
                        .WithMany("TownEvents")
                        .HasForeignKey("UserId");

                    b.Navigation("Town");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwitchGames.Ttny.Dal.Entities.TownUserEntity.TownUser", b =>
                {
                    b.HasOne("TwitchGames.Ttny.Dal.Entities.TownEntity.Town", "Town")
                        .WithMany("TownUsers")
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TwitchGames.Ttny.Dal.Entities.UserEntity.User", "User")
                        .WithMany("TownUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Town");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwitchGames.Ttny.Dal.Entities.TownEntity.Town", b =>
                {
                    b.Navigation("TownEvents");

                    b.Navigation("TownUsers");
                });

            modelBuilder.Entity("TwitchGames.Ttny.Dal.Entities.UserEntity.User", b =>
                {
                    b.Navigation("TownEvents");

                    b.Navigation("TownUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
